//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballNeighborhood.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MatchesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatchesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballNeighborhood.Resources.MatchesResources", typeof(MatchesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie posiadasz praw do edycji tego spotkanie.
        /// </summary>
        public static string InsufficientPrivileges_ErrorMessage {
            get {
                return ResourceManager.GetString("InsufficientPrivileges_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotkanie zostało usunięte.
        /// </summary>
        public static string MatchDeleted_Message {
            get {
                return ResourceManager.GetString("MatchDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotkanie nie istnieje.
        /// </summary>
        public static string MatchDoesNotExists_ErrorMessage {
            get {
                return ResourceManager.GetString("MatchDoesNotExists_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotkanie zostało utworzone.
        /// </summary>
        public static string MatchHasBeenCreated {
            get {
                return ResourceManager.GetString("MatchHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotkanie zostało zaktualizowane.
        /// </summary>
        public static string MatchHasBeenUpdated {
            get {
                return ResourceManager.GetString("MatchHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik z rolą zawodnik nie możę tworzyć spotkań.
        /// </summary>
        public static string PlayerCannotCreateMaches_ErrorMessage {
            get {
                return ResourceManager.GetString("PlayerCannotCreateMaches_ErrorMessage", resourceCulture);
            }
        }
    }
}
